//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarlockSoft.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/IniciarSesion")]
        public string WarlockSoft_WS_IniciarSesion_IniciarSesion {
            get {
                return ((string)(this["WarlockSoft_WS_IniciarSesion_IniciarSesion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/CrearCuenta")]
        public string WarlockSoft_WS_CrearCuenta_CrearCuenta {
            get {
                return ((string)(this["WarlockSoft_WS_CrearCuenta_CrearCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/BuscarUsuario")]
        public string WarlockSoft_WS_BuscarUsuario_BuscarUsuario {
            get {
                return ((string)(this["WarlockSoft_WS_BuscarUsuario_BuscarUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/VerPerfil")]
        public string WarlockSoft_VerPerfil_VerPerfil {
            get {
                return ((string)(this["WarlockSoft_VerPerfil_VerPerfil"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/PublicarEstado")]
        public string WarlockSoft_PublicarEstado_PublicarEstado {
            get {
                return ((string)(this["WarlockSoft_PublicarEstado_PublicarEstado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/AgregarConocimiento")]
        public string WarlockSoft_WS_AgregarConocimiento_AgregarConocimiento {
            get {
                return ((string)(this["WarlockSoft_WS_AgregarConocimiento_AgregarConocimiento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/EliminarConocimiento")]
        public string WarlockSoft_WS_EliminarConocimiento_EliminarConocimiento {
            get {
                return ((string)(this["WarlockSoft_WS_EliminarConocimiento_EliminarConocimiento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/VotarConocimiento")]
        public string WarlockSoft_WS_VotarConocimiento_VotarConocimiento {
            get {
                return ((string)(this["WarlockSoft_WS_VotarConocimiento_VotarConocimiento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/AgregarContacto")]
        public string WarlockSoft_WS_AgregarContacto_AgregarContacto {
            get {
                return ((string)(this["WarlockSoft_WS_AgregarContacto_AgregarContacto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/EliminarContacto")]
        public string WarlockSoft_WS_EliminarContacto_EliminarContacto {
            get {
                return ((string)(this["WarlockSoft_WS_EliminarContacto_EliminarContacto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/CrearProyecto")]
        public string WarlockSoft_WS_CrearProyecto_CrearProyecto {
            get {
                return ((string)(this["WarlockSoft_WS_CrearProyecto_CrearProyecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/CrearTareaProyecto")]
        public string WarlockSoft_WS_AgregarTareaProyecto_CrearTareaProyecto {
            get {
                return ((string)(this["WarlockSoft_WS_AgregarTareaProyecto_CrearTareaProyecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/CrearAsociacion")]
        public string WarlockSoft_WS_CrearAsociacion_CrearAsociacion {
            get {
                return ((string)(this["WarlockSoft_WS_CrearAsociacion_CrearAsociacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/InvitarAsociacion")]
        public string WarlockSoft_WS_InvitarAsociacion_InvitarAsociacion {
            get {
                return ((string)(this["WarlockSoft_WS_InvitarAsociacion_InvitarAsociacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/EliminarMiembro")]
        public string WarlockSoft_WS_EliminarMiembro_EliminarMiembro {
            get {
                return ((string)(this["WarlockSoft_WS_EliminarMiembro_EliminarMiembro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/SolicitarUnionTarea")]
        public string WarlockSoft_WS_SolicitarUnionTarea_SolicitarUnionTarea {
            get {
                return ((string)(this["WarlockSoft_WS_SolicitarUnionTarea_SolicitarUnionTarea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/AdminIngresarUsuarioAsociacion")]
        public string WarlockSoft_WS_CargarUsuariosAsociaciones_AdminIngresarUsuarioAsociacion {
            get {
                return ((string)(this["WarlockSoft_WS_CargarUsuariosAsociaciones_AdminIngresarUsuarioAsociacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/AdminIngresarEstadoComentario")]
        public string WarlockSoft_WS_CargaEstadosComentarios_AdminIngresarEstadoComentario {
            get {
                return ((string)(this["WarlockSoft_WS_CargaEstadosComentarios_AdminIngresarEstadoComentario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/AdminIngresarProyecto")]
        public string WarlockSoft_WS_CargarProyectos_AdminIngresarProyecto {
            get {
                return ((string)(this["WarlockSoft_WS_CargarProyectos_AdminIngresarProyecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/MostrarProyectosActivos")]
        public string WarlockSoft_WS_ObtenerProyectosActivos_MostrarProyectosActivos {
            get {
                return ((string)(this["WarlockSoft_WS_ObtenerProyectosActivos_MostrarProyectosActivos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/MostrarTareasEstado")]
        public string WarlockSoft_WS_MostrarTareasEstado_MostrarTareasEstado {
            get {
                return ((string)(this["WarlockSoft_WS_MostrarTareasEstado_MostrarTareasEstado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/Denunciar")]
        public string WarlockSoft_WS_Denunciar_Denunciar {
            get {
                return ((string)(this["WarlockSoft_WS_Denunciar_Denunciar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/WarlockSoft/Extras")]
        public string WarlockSoft_WS_Extras_Extras {
            get {
                return ((string)(this["WarlockSoft_WS_Extras_Extras"]));
            }
        }
    }
}
