//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.WS_Denunciar {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DenunciarPortBinding", Namespace="http://WarlockSoft/")]
    public partial class Denunciar : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerDenunciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAsociacionDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DenunciarCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPerfilDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerProyectoDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Denunciar() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_WS_Denunciar_Denunciar;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerDenunciasCompletedEventHandler ObtenerDenunciasCompleted;
        
        /// <remarks/>
        public event ObtenerAsociacionDCompletedEventHandler ObtenerAsociacionDCompleted;
        
        /// <remarks/>
        public event DenunciarCCCompletedEventHandler DenunciarCCCompleted;
        
        /// <remarks/>
        public event ObtenerPerfilDCompletedEventHandler ObtenerPerfilDCompleted;
        
        /// <remarks/>
        public event ObtenerProyectoDCompletedEventHandler ObtenerProyectoDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerDenuncias() {
            object[] results = this.Invoke("ObtenerDenuncias", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDenunciasAsync() {
            this.ObtenerDenunciasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerDenunciasAsync(object userState) {
            if ((this.ObtenerDenunciasOperationCompleted == null)) {
                this.ObtenerDenunciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDenunciasOperationCompleted);
            }
            this.InvokeAsync("ObtenerDenuncias", new object[0], this.ObtenerDenunciasOperationCompleted, userState);
        }
        
        private void OnObtenerDenunciasOperationCompleted(object arg) {
            if ((this.ObtenerDenunciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDenunciasCompleted(this, new ObtenerDenunciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerAsociacionD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDA) {
            object[] results = this.Invoke("ObtenerAsociacionD", new object[] {
                        IDA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAsociacionDAsync(string IDA) {
            this.ObtenerAsociacionDAsync(IDA, null);
        }
        
        /// <remarks/>
        public void ObtenerAsociacionDAsync(string IDA, object userState) {
            if ((this.ObtenerAsociacionDOperationCompleted == null)) {
                this.ObtenerAsociacionDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAsociacionDOperationCompleted);
            }
            this.InvokeAsync("ObtenerAsociacionD", new object[] {
                        IDA}, this.ObtenerAsociacionDOperationCompleted, userState);
        }
        
        private void OnObtenerAsociacionDOperationCompleted(object arg) {
            if ((this.ObtenerAsociacionDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAsociacionDCompleted(this, new ObtenerAsociacionDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DenunciarCC([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Elemento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreElemento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Motivo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Denunciante) {
            object[] results = this.Invoke("DenunciarCC", new object[] {
                        Elemento,
                        NombreElemento,
                        Motivo,
                        Denunciante});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DenunciarCCAsync(string Elemento, string NombreElemento, string Motivo, string Denunciante) {
            this.DenunciarCCAsync(Elemento, NombreElemento, Motivo, Denunciante, null);
        }
        
        /// <remarks/>
        public void DenunciarCCAsync(string Elemento, string NombreElemento, string Motivo, string Denunciante, object userState) {
            if ((this.DenunciarCCOperationCompleted == null)) {
                this.DenunciarCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDenunciarCCOperationCompleted);
            }
            this.InvokeAsync("DenunciarCC", new object[] {
                        Elemento,
                        NombreElemento,
                        Motivo,
                        Denunciante}, this.DenunciarCCOperationCompleted, userState);
        }
        
        private void OnDenunciarCCOperationCompleted(object arg) {
            if ((this.DenunciarCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DenunciarCCCompleted(this, new DenunciarCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerPerfilD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDU) {
            object[] results = this.Invoke("ObtenerPerfilD", new object[] {
                        IDU});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPerfilDAsync(string IDU) {
            this.ObtenerPerfilDAsync(IDU, null);
        }
        
        /// <remarks/>
        public void ObtenerPerfilDAsync(string IDU, object userState) {
            if ((this.ObtenerPerfilDOperationCompleted == null)) {
                this.ObtenerPerfilDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPerfilDOperationCompleted);
            }
            this.InvokeAsync("ObtenerPerfilD", new object[] {
                        IDU}, this.ObtenerPerfilDOperationCompleted, userState);
        }
        
        private void OnObtenerPerfilDOperationCompleted(object arg) {
            if ((this.ObtenerPerfilDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPerfilDCompleted(this, new ObtenerPerfilDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerProyectoD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDP) {
            object[] results = this.Invoke("ObtenerProyectoD", new object[] {
                        IDP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerProyectoDAsync(string IDP) {
            this.ObtenerProyectoDAsync(IDP, null);
        }
        
        /// <remarks/>
        public void ObtenerProyectoDAsync(string IDP, object userState) {
            if ((this.ObtenerProyectoDOperationCompleted == null)) {
                this.ObtenerProyectoDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerProyectoDOperationCompleted);
            }
            this.InvokeAsync("ObtenerProyectoD", new object[] {
                        IDP}, this.ObtenerProyectoDOperationCompleted, userState);
        }
        
        private void OnObtenerProyectoDOperationCompleted(object arg) {
            if ((this.ObtenerProyectoDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerProyectoDCompleted(this, new ObtenerProyectoDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerDenunciasCompletedEventHandler(object sender, ObtenerDenunciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDenunciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDenunciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerAsociacionDCompletedEventHandler(object sender, ObtenerAsociacionDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAsociacionDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAsociacionDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DenunciarCCCompletedEventHandler(object sender, DenunciarCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DenunciarCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DenunciarCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerPerfilDCompletedEventHandler(object sender, ObtenerPerfilDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPerfilDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPerfilDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerProyectoDCompletedEventHandler(object sender, ObtenerProyectoDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerProyectoDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerProyectoDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591