//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.WS_InvitarAsociacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InvitarAsociacionPortBinding", Namespace="http://WarlockSoft/")]
    public partial class InvitarAsociacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarInvitacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarMiembroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerRolAsociacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerMiembrosAsociacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InvitarAsociacion() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_WS_InvitarAsociacion_InvitarAsociacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarInvitacionCompletedEventHandler EnviarInvitacionCompleted;
        
        /// <remarks/>
        public event VerificarMiembroCompletedEventHandler VerificarMiembroCompleted;
        
        /// <remarks/>
        public event ObtenerRolAsociacionCompletedEventHandler ObtenerRolAsociacionCompleted;
        
        /// <remarks/>
        public event ObtenerMiembrosAsociacionCompletedEventHandler ObtenerMiembrosAsociacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EnviarInvitacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDAsociacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("EnviarInvitacion", new object[] {
                        IDAsociacion,
                        Usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarInvitacionAsync(string IDAsociacion, string Usuario) {
            this.EnviarInvitacionAsync(IDAsociacion, Usuario, null);
        }
        
        /// <remarks/>
        public void EnviarInvitacionAsync(string IDAsociacion, string Usuario, object userState) {
            if ((this.EnviarInvitacionOperationCompleted == null)) {
                this.EnviarInvitacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarInvitacionOperationCompleted);
            }
            this.InvokeAsync("EnviarInvitacion", new object[] {
                        IDAsociacion,
                        Usuario}, this.EnviarInvitacionOperationCompleted, userState);
        }
        
        private void OnEnviarInvitacionOperationCompleted(object arg) {
            if ((this.EnviarInvitacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarInvitacionCompleted(this, new EnviarInvitacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool VerificarMiembro([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDAsociacion) {
            object[] results = this.Invoke("VerificarMiembro", new object[] {
                        Usuario,
                        IDAsociacion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarMiembroAsync(string Usuario, string IDAsociacion) {
            this.VerificarMiembroAsync(Usuario, IDAsociacion, null);
        }
        
        /// <remarks/>
        public void VerificarMiembroAsync(string Usuario, string IDAsociacion, object userState) {
            if ((this.VerificarMiembroOperationCompleted == null)) {
                this.VerificarMiembroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarMiembroOperationCompleted);
            }
            this.InvokeAsync("VerificarMiembro", new object[] {
                        Usuario,
                        IDAsociacion}, this.VerificarMiembroOperationCompleted, userState);
        }
        
        private void OnVerificarMiembroOperationCompleted(object arg) {
            if ((this.VerificarMiembroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarMiembroCompleted(this, new VerificarMiembroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerRolAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDUsuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDAsociacion) {
            object[] results = this.Invoke("ObtenerRolAsociacion", new object[] {
                        IDUsuario,
                        IDAsociacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerRolAsociacionAsync(string IDUsuario, string IDAsociacion) {
            this.ObtenerRolAsociacionAsync(IDUsuario, IDAsociacion, null);
        }
        
        /// <remarks/>
        public void ObtenerRolAsociacionAsync(string IDUsuario, string IDAsociacion, object userState) {
            if ((this.ObtenerRolAsociacionOperationCompleted == null)) {
                this.ObtenerRolAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRolAsociacionOperationCompleted);
            }
            this.InvokeAsync("ObtenerRolAsociacion", new object[] {
                        IDUsuario,
                        IDAsociacion}, this.ObtenerRolAsociacionOperationCompleted, userState);
        }
        
        private void OnObtenerRolAsociacionOperationCompleted(object arg) {
            if ((this.ObtenerRolAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerRolAsociacionCompleted(this, new ObtenerRolAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerMiembrosAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDAsociacion) {
            object[] results = this.Invoke("ObtenerMiembrosAsociacion", new object[] {
                        IDAsociacion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerMiembrosAsociacionAsync(string IDAsociacion) {
            this.ObtenerMiembrosAsociacionAsync(IDAsociacion, null);
        }
        
        /// <remarks/>
        public void ObtenerMiembrosAsociacionAsync(string IDAsociacion, object userState) {
            if ((this.ObtenerMiembrosAsociacionOperationCompleted == null)) {
                this.ObtenerMiembrosAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerMiembrosAsociacionOperationCompleted);
            }
            this.InvokeAsync("ObtenerMiembrosAsociacion", new object[] {
                        IDAsociacion}, this.ObtenerMiembrosAsociacionOperationCompleted, userState);
        }
        
        private void OnObtenerMiembrosAsociacionOperationCompleted(object arg) {
            if ((this.ObtenerMiembrosAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerMiembrosAsociacionCompleted(this, new ObtenerMiembrosAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void EnviarInvitacionCompletedEventHandler(object sender, EnviarInvitacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarInvitacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarInvitacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarMiembroCompletedEventHandler(object sender, VerificarMiembroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarMiembroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarMiembroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerRolAsociacionCompletedEventHandler(object sender, ObtenerRolAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerRolAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerRolAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerMiembrosAsociacionCompletedEventHandler(object sender, ObtenerMiembrosAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerMiembrosAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerMiembrosAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591