//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.WS_AgregarConocimiento {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgregarConocimientoPortBinding", Namespace="http://WarlockSoft/")]
    public partial class AgregarConocimiento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerConocimientosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerIDHabilidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarConocimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerIDConocimientosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerKarmaConocimientosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarConocimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerIDConocimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarHabilidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerConocimientosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarHabilidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgregarConocimiento() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_WS_AgregarConocimiento_AgregarConocimiento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerConocimientosCompletedEventHandler ObtenerConocimientosCompleted;
        
        /// <remarks/>
        public event ObtenerIDHabilidadCompletedEventHandler ObtenerIDHabilidadCompleted;
        
        /// <remarks/>
        public event GuardarConocimientoCompletedEventHandler GuardarConocimientoCompleted;
        
        /// <remarks/>
        public event ObtenerIDConocimientosUsuarioCompletedEventHandler ObtenerIDConocimientosUsuarioCompleted;
        
        /// <remarks/>
        public event ObtenerKarmaConocimientosUsuarioCompletedEventHandler ObtenerKarmaConocimientosUsuarioCompleted;
        
        /// <remarks/>
        public event VerificarConocimientoCompletedEventHandler VerificarConocimientoCompleted;
        
        /// <remarks/>
        public event ObtenerIDConocimientoCompletedEventHandler ObtenerIDConocimientoCompleted;
        
        /// <remarks/>
        public event VerificarHabilidadCompletedEventHandler VerificarHabilidadCompleted;
        
        /// <remarks/>
        public event ObtenerConocimientosUsuarioCompletedEventHandler ObtenerConocimientosUsuarioCompleted;
        
        /// <remarks/>
        public event GuardarHabilidadCompletedEventHandler GuardarHabilidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerConocimientos() {
            object[] results = this.Invoke("ObtenerConocimientos", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerConocimientosAsync() {
            this.ObtenerConocimientosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerConocimientosAsync(object userState) {
            if ((this.ObtenerConocimientosOperationCompleted == null)) {
                this.ObtenerConocimientosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerConocimientosOperationCompleted);
            }
            this.InvokeAsync("ObtenerConocimientos", new object[0], this.ObtenerConocimientosOperationCompleted, userState);
        }
        
        private void OnObtenerConocimientosOperationCompleted(object arg) {
            if ((this.ObtenerConocimientosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerConocimientosCompleted(this, new ObtenerConocimientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerIDHabilidad([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Conocimiento) {
            object[] results = this.Invoke("ObtenerIDHabilidad", new object[] {
                        Conocimiento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerIDHabilidadAsync(string Conocimiento) {
            this.ObtenerIDHabilidadAsync(Conocimiento, null);
        }
        
        /// <remarks/>
        public void ObtenerIDHabilidadAsync(string Conocimiento, object userState) {
            if ((this.ObtenerIDHabilidadOperationCompleted == null)) {
                this.ObtenerIDHabilidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerIDHabilidadOperationCompleted);
            }
            this.InvokeAsync("ObtenerIDHabilidad", new object[] {
                        Conocimiento}, this.ObtenerIDHabilidadOperationCompleted, userState);
        }
        
        private void OnObtenerIDHabilidadOperationCompleted(object arg) {
            if ((this.ObtenerIDHabilidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerIDHabilidadCompleted(this, new ObtenerIDHabilidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool GuardarConocimiento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Conocimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("GuardarConocimiento", new object[] {
                        Conocimiento,
                        Usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarConocimientoAsync(string Conocimiento, string Usuario) {
            this.GuardarConocimientoAsync(Conocimiento, Usuario, null);
        }
        
        /// <remarks/>
        public void GuardarConocimientoAsync(string Conocimiento, string Usuario, object userState) {
            if ((this.GuardarConocimientoOperationCompleted == null)) {
                this.GuardarConocimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarConocimientoOperationCompleted);
            }
            this.InvokeAsync("GuardarConocimiento", new object[] {
                        Conocimiento,
                        Usuario}, this.GuardarConocimientoOperationCompleted, userState);
        }
        
        private void OnGuardarConocimientoOperationCompleted(object arg) {
            if ((this.GuardarConocimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarConocimientoCompleted(this, new GuardarConocimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerIDConocimientosUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("ObtenerIDConocimientosUsuario", new object[] {
                        Usuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerIDConocimientosUsuarioAsync(string Usuario) {
            this.ObtenerIDConocimientosUsuarioAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void ObtenerIDConocimientosUsuarioAsync(string Usuario, object userState) {
            if ((this.ObtenerIDConocimientosUsuarioOperationCompleted == null)) {
                this.ObtenerIDConocimientosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerIDConocimientosUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerIDConocimientosUsuario", new object[] {
                        Usuario}, this.ObtenerIDConocimientosUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerIDConocimientosUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerIDConocimientosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerIDConocimientosUsuarioCompleted(this, new ObtenerIDConocimientosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerKarmaConocimientosUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("ObtenerKarmaConocimientosUsuario", new object[] {
                        Usuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerKarmaConocimientosUsuarioAsync(string Usuario) {
            this.ObtenerKarmaConocimientosUsuarioAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void ObtenerKarmaConocimientosUsuarioAsync(string Usuario, object userState) {
            if ((this.ObtenerKarmaConocimientosUsuarioOperationCompleted == null)) {
                this.ObtenerKarmaConocimientosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerKarmaConocimientosUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerKarmaConocimientosUsuario", new object[] {
                        Usuario}, this.ObtenerKarmaConocimientosUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerKarmaConocimientosUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerKarmaConocimientosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerKarmaConocimientosUsuarioCompleted(this, new ObtenerKarmaConocimientosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool VerificarConocimiento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Conocimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("VerificarConocimiento", new object[] {
                        Conocimiento,
                        Usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarConocimientoAsync(string Conocimiento, string Usuario) {
            this.VerificarConocimientoAsync(Conocimiento, Usuario, null);
        }
        
        /// <remarks/>
        public void VerificarConocimientoAsync(string Conocimiento, string Usuario, object userState) {
            if ((this.VerificarConocimientoOperationCompleted == null)) {
                this.VerificarConocimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarConocimientoOperationCompleted);
            }
            this.InvokeAsync("VerificarConocimiento", new object[] {
                        Conocimiento,
                        Usuario}, this.VerificarConocimientoOperationCompleted, userState);
        }
        
        private void OnVerificarConocimientoOperationCompleted(object arg) {
            if ((this.VerificarConocimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarConocimientoCompleted(this, new VerificarConocimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerIDConocimiento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Conocimiento) {
            object[] results = this.Invoke("ObtenerIDConocimiento", new object[] {
                        Conocimiento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerIDConocimientoAsync(string Conocimiento) {
            this.ObtenerIDConocimientoAsync(Conocimiento, null);
        }
        
        /// <remarks/>
        public void ObtenerIDConocimientoAsync(string Conocimiento, object userState) {
            if ((this.ObtenerIDConocimientoOperationCompleted == null)) {
                this.ObtenerIDConocimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerIDConocimientoOperationCompleted);
            }
            this.InvokeAsync("ObtenerIDConocimiento", new object[] {
                        Conocimiento}, this.ObtenerIDConocimientoOperationCompleted, userState);
        }
        
        private void OnObtenerIDConocimientoOperationCompleted(object arg) {
            if ((this.ObtenerIDConocimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerIDConocimientoCompleted(this, new ObtenerIDConocimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool VerificarHabilidad([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Habilidad, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario) {
            object[] results = this.Invoke("VerificarHabilidad", new object[] {
                        Habilidad,
                        Usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarHabilidadAsync(string Habilidad, string Usuario) {
            this.VerificarHabilidadAsync(Habilidad, Usuario, null);
        }
        
        /// <remarks/>
        public void VerificarHabilidadAsync(string Habilidad, string Usuario, object userState) {
            if ((this.VerificarHabilidadOperationCompleted == null)) {
                this.VerificarHabilidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarHabilidadOperationCompleted);
            }
            this.InvokeAsync("VerificarHabilidad", new object[] {
                        Habilidad,
                        Usuario}, this.VerificarHabilidadOperationCompleted, userState);
        }
        
        private void OnVerificarHabilidadOperationCompleted(object arg) {
            if ((this.VerificarHabilidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarHabilidadCompleted(this, new VerificarHabilidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerConocimientosUsuario([System.Xml.Serialization.XmlElementAttribute("IDConocimientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] IDConocimientos) {
            object[] results = this.Invoke("ObtenerConocimientosUsuario", new object[] {
                        IDConocimientos});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerConocimientosUsuarioAsync(string[] IDConocimientos) {
            this.ObtenerConocimientosUsuarioAsync(IDConocimientos, null);
        }
        
        /// <remarks/>
        public void ObtenerConocimientosUsuarioAsync(string[] IDConocimientos, object userState) {
            if ((this.ObtenerConocimientosUsuarioOperationCompleted == null)) {
                this.ObtenerConocimientosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerConocimientosUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerConocimientosUsuario", new object[] {
                        IDConocimientos}, this.ObtenerConocimientosUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerConocimientosUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerConocimientosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerConocimientosUsuarioCompleted(this, new ObtenerConocimientosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool GuardarHabilidad([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Habilidad) {
            object[] results = this.Invoke("GuardarHabilidad", new object[] {
                        Usuario,
                        Habilidad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarHabilidadAsync(string Usuario, string Habilidad) {
            this.GuardarHabilidadAsync(Usuario, Habilidad, null);
        }
        
        /// <remarks/>
        public void GuardarHabilidadAsync(string Usuario, string Habilidad, object userState) {
            if ((this.GuardarHabilidadOperationCompleted == null)) {
                this.GuardarHabilidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarHabilidadOperationCompleted);
            }
            this.InvokeAsync("GuardarHabilidad", new object[] {
                        Usuario,
                        Habilidad}, this.GuardarHabilidadOperationCompleted, userState);
        }
        
        private void OnGuardarHabilidadOperationCompleted(object arg) {
            if ((this.GuardarHabilidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarHabilidadCompleted(this, new GuardarHabilidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerConocimientosCompletedEventHandler(object sender, ObtenerConocimientosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerConocimientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerConocimientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerIDHabilidadCompletedEventHandler(object sender, ObtenerIDHabilidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerIDHabilidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerIDHabilidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GuardarConocimientoCompletedEventHandler(object sender, GuardarConocimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarConocimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarConocimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerIDConocimientosUsuarioCompletedEventHandler(object sender, ObtenerIDConocimientosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerIDConocimientosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerIDConocimientosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerKarmaConocimientosUsuarioCompletedEventHandler(object sender, ObtenerKarmaConocimientosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerKarmaConocimientosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerKarmaConocimientosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarConocimientoCompletedEventHandler(object sender, VerificarConocimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarConocimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarConocimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerIDConocimientoCompletedEventHandler(object sender, ObtenerIDConocimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerIDConocimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerIDConocimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarHabilidadCompletedEventHandler(object sender, VerificarHabilidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarHabilidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarHabilidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerConocimientosUsuarioCompletedEventHandler(object sender, ObtenerConocimientosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerConocimientosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerConocimientosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GuardarHabilidadCompletedEventHandler(object sender, GuardarHabilidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarHabilidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarHabilidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591