//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.WS_AgregarContacto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgregarContactoPortBinding", Namespace="http://WarlockSoft/")]
    public partial class AgregarContacto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComprobarAmistadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarAmigoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerListaContactosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNombreUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgregarContacto() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_WS_AgregarContacto_AgregarContacto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComprobarAmistadCompletedEventHandler ComprobarAmistadCompleted;
        
        /// <remarks/>
        public event GuardarAmigoCompletedEventHandler GuardarAmigoCompleted;
        
        /// <remarks/>
        public event ObtenerListaContactosCompletedEventHandler ObtenerListaContactosCompleted;
        
        /// <remarks/>
        public event ObtenerNombreUsuarioCompletedEventHandler ObtenerNombreUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ComprobarAmistad([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDUsuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreUsuario) {
            object[] results = this.Invoke("ComprobarAmistad", new object[] {
                        IDUsuario,
                        NombreUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ComprobarAmistadAsync(string IDUsuario, string NombreUsuario) {
            this.ComprobarAmistadAsync(IDUsuario, NombreUsuario, null);
        }
        
        /// <remarks/>
        public void ComprobarAmistadAsync(string IDUsuario, string NombreUsuario, object userState) {
            if ((this.ComprobarAmistadOperationCompleted == null)) {
                this.ComprobarAmistadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComprobarAmistadOperationCompleted);
            }
            this.InvokeAsync("ComprobarAmistad", new object[] {
                        IDUsuario,
                        NombreUsuario}, this.ComprobarAmistadOperationCompleted, userState);
        }
        
        private void OnComprobarAmistadOperationCompleted(object arg) {
            if ((this.ComprobarAmistadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComprobarAmistadCompleted(this, new ComprobarAmistadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool GuardarAmigo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDUsuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreContacto) {
            object[] results = this.Invoke("GuardarAmigo", new object[] {
                        IDUsuario,
                        NombreContacto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAmigoAsync(string IDUsuario, string NombreContacto) {
            this.GuardarAmigoAsync(IDUsuario, NombreContacto, null);
        }
        
        /// <remarks/>
        public void GuardarAmigoAsync(string IDUsuario, string NombreContacto, object userState) {
            if ((this.GuardarAmigoOperationCompleted == null)) {
                this.GuardarAmigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarAmigoOperationCompleted);
            }
            this.InvokeAsync("GuardarAmigo", new object[] {
                        IDUsuario,
                        NombreContacto}, this.GuardarAmigoOperationCompleted, userState);
        }
        
        private void OnGuardarAmigoOperationCompleted(object arg) {
            if ((this.GuardarAmigoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarAmigoCompleted(this, new GuardarAmigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerListaContactos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDUsuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreUsuario) {
            object[] results = this.Invoke("ObtenerListaContactos", new object[] {
                        IDUsuario,
                        NombreUsuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerListaContactosAsync(string IDUsuario, string NombreUsuario) {
            this.ObtenerListaContactosAsync(IDUsuario, NombreUsuario, null);
        }
        
        /// <remarks/>
        public void ObtenerListaContactosAsync(string IDUsuario, string NombreUsuario, object userState) {
            if ((this.ObtenerListaContactosOperationCompleted == null)) {
                this.ObtenerListaContactosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerListaContactosOperationCompleted);
            }
            this.InvokeAsync("ObtenerListaContactos", new object[] {
                        IDUsuario,
                        NombreUsuario}, this.ObtenerListaContactosOperationCompleted, userState);
        }
        
        private void OnObtenerListaContactosOperationCompleted(object arg) {
            if ((this.ObtenerListaContactosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerListaContactosCompleted(this, new ObtenerListaContactosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerNombreUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDUsuarioV) {
            object[] results = this.Invoke("ObtenerNombreUsuario", new object[] {
                        IDUsuarioV});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNombreUsuarioAsync(string IDUsuarioV) {
            this.ObtenerNombreUsuarioAsync(IDUsuarioV, null);
        }
        
        /// <remarks/>
        public void ObtenerNombreUsuarioAsync(string IDUsuarioV, object userState) {
            if ((this.ObtenerNombreUsuarioOperationCompleted == null)) {
                this.ObtenerNombreUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNombreUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerNombreUsuario", new object[] {
                        IDUsuarioV}, this.ObtenerNombreUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerNombreUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerNombreUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNombreUsuarioCompleted(this, new ObtenerNombreUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ComprobarAmistadCompletedEventHandler(object sender, ComprobarAmistadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComprobarAmistadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComprobarAmistadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GuardarAmigoCompletedEventHandler(object sender, GuardarAmigoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarAmigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarAmigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerListaContactosCompletedEventHandler(object sender, ObtenerListaContactosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerListaContactosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerListaContactosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerNombreUsuarioCompletedEventHandler(object sender, ObtenerNombreUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNombreUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNombreUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591