//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WarlockSoft.WS_AgregarTareaProyecto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CrearTareaProyectoPortBinding", Namespace="http://WarlockSoft/")]
    public partial class CrearTareaProyecto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerEstadoTareasProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerConocimientosTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTareasProyectoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarTareaProyectoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CrearTareaProyecto() {
            this.Url = global::WarlockSoft.Properties.Settings.Default.WarlockSoft_WS_AgregarTareaProyecto_CrearTareaProyecto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerEstadoTareasProyectoCompletedEventHandler ObtenerEstadoTareasProyectoCompleted;
        
        /// <remarks/>
        public event ObtenerConocimientosTareaCompletedEventHandler ObtenerConocimientosTareaCompleted;
        
        /// <remarks/>
        public event ObtenerTareasProyectoCompletedEventHandler ObtenerTareasProyectoCompleted;
        
        /// <remarks/>
        public event GuardarTareaProyectoCompletedEventHandler GuardarTareaProyectoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerEstadoTareasProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDProyecto) {
            object[] results = this.Invoke("ObtenerEstadoTareasProyecto", new object[] {
                        IDProyecto});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerEstadoTareasProyectoAsync(string IDProyecto) {
            this.ObtenerEstadoTareasProyectoAsync(IDProyecto, null);
        }
        
        /// <remarks/>
        public void ObtenerEstadoTareasProyectoAsync(string IDProyecto, object userState) {
            if ((this.ObtenerEstadoTareasProyectoOperationCompleted == null)) {
                this.ObtenerEstadoTareasProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEstadoTareasProyectoOperationCompleted);
            }
            this.InvokeAsync("ObtenerEstadoTareasProyecto", new object[] {
                        IDProyecto}, this.ObtenerEstadoTareasProyectoOperationCompleted, userState);
        }
        
        private void OnObtenerEstadoTareasProyectoOperationCompleted(object arg) {
            if ((this.ObtenerEstadoTareasProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEstadoTareasProyectoCompleted(this, new ObtenerEstadoTareasProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerConocimientosTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDProyecto) {
            object[] results = this.Invoke("ObtenerConocimientosTarea", new object[] {
                        IDProyecto});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerConocimientosTareaAsync(string IDProyecto) {
            this.ObtenerConocimientosTareaAsync(IDProyecto, null);
        }
        
        /// <remarks/>
        public void ObtenerConocimientosTareaAsync(string IDProyecto, object userState) {
            if ((this.ObtenerConocimientosTareaOperationCompleted == null)) {
                this.ObtenerConocimientosTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerConocimientosTareaOperationCompleted);
            }
            this.InvokeAsync("ObtenerConocimientosTarea", new object[] {
                        IDProyecto}, this.ObtenerConocimientosTareaOperationCompleted, userState);
        }
        
        private void OnObtenerConocimientosTareaOperationCompleted(object arg) {
            if ((this.ObtenerConocimientosTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerConocimientosTareaCompleted(this, new ObtenerConocimientosTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ObtenerTareasProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDProyecto) {
            object[] results = this.Invoke("ObtenerTareasProyecto", new object[] {
                        IDProyecto});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTareasProyectoAsync(string IDProyecto) {
            this.ObtenerTareasProyectoAsync(IDProyecto, null);
        }
        
        /// <remarks/>
        public void ObtenerTareasProyectoAsync(string IDProyecto, object userState) {
            if ((this.ObtenerTareasProyectoOperationCompleted == null)) {
                this.ObtenerTareasProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTareasProyectoOperationCompleted);
            }
            this.InvokeAsync("ObtenerTareasProyecto", new object[] {
                        IDProyecto}, this.ObtenerTareasProyectoOperationCompleted, userState);
        }
        
        private void OnObtenerTareasProyectoOperationCompleted(object arg) {
            if ((this.ObtenerTareasProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTareasProyectoCompleted(this, new ObtenerTareasProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WarlockSoft/", ResponseNamespace="http://WarlockSoft/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool GuardarTareaProyecto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Descripcion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaInicio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDProyecto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Conocimiento) {
            object[] results = this.Invoke("GuardarTareaProyecto", new object[] {
                        Nombre,
                        Descripcion,
                        FechaInicio,
                        IDProyecto,
                        Conocimiento});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarTareaProyectoAsync(string Nombre, string Descripcion, string FechaInicio, string IDProyecto, string Conocimiento) {
            this.GuardarTareaProyectoAsync(Nombre, Descripcion, FechaInicio, IDProyecto, Conocimiento, null);
        }
        
        /// <remarks/>
        public void GuardarTareaProyectoAsync(string Nombre, string Descripcion, string FechaInicio, string IDProyecto, string Conocimiento, object userState) {
            if ((this.GuardarTareaProyectoOperationCompleted == null)) {
                this.GuardarTareaProyectoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarTareaProyectoOperationCompleted);
            }
            this.InvokeAsync("GuardarTareaProyecto", new object[] {
                        Nombre,
                        Descripcion,
                        FechaInicio,
                        IDProyecto,
                        Conocimiento}, this.GuardarTareaProyectoOperationCompleted, userState);
        }
        
        private void OnGuardarTareaProyectoOperationCompleted(object arg) {
            if ((this.GuardarTareaProyectoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarTareaProyectoCompleted(this, new GuardarTareaProyectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerEstadoTareasProyectoCompletedEventHandler(object sender, ObtenerEstadoTareasProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEstadoTareasProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEstadoTareasProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerConocimientosTareaCompletedEventHandler(object sender, ObtenerConocimientosTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerConocimientosTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerConocimientosTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerTareasProyectoCompletedEventHandler(object sender, ObtenerTareasProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTareasProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTareasProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GuardarTareaProyectoCompletedEventHandler(object sender, GuardarTareaProyectoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarTareaProyectoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarTareaProyectoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591